[package]
name = "gitrel"
version = "0.1.0"
authors = ["Evgenii Grigorev <zjekadev@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "Install and manage binaries via GitHub releases"
homepage = "https://github.com/izirku/gitrel"
repository = "https://github.com/izirku/gitrel"
documentation = "https://docs.rs/gitrel"
categories = ["command-line-utilities"]
readme = "crates-io.md"
include = ["src/**/*.rs", "crates-io.md", "README.md", "LICENSE-APACHE", "LICENSE-MIT"] 

[dependencies]
anyhow = "1.0.44"
colored = "2.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.0-beta.4", features = ["yaml"] }
directories = "4.0.1"
lazy_static = "1.4.0"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["json"] }
semver = "1.0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["full"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
url = { version = "2.2.2", features = ["serde"] }
tempfile = "3.2.0"
bzip2 = "0.4.3"
xz = "0.1.0"
zip = "0.5.13"
zip-extensions = "0.6.1"
tar = "0.4.37"
flate2 = "1.0.22"

[build-dependencies]
platforms = "1.1.0"
lazy_static = "1.4.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
