[package]
name = "gitrel"
version = "0.1.0"
authors = ["Evgenii Grigorev <zjekadev@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "Install and manage binaries via GitHub releases"
homepage = "https://github.com/izirku/gitrel"
repository = "https://github.com/izirku/gitrel"
documentation = "https://docs.rs/gitrel"
categories = ["command-line-utilities"]
readme = "crates-io.md"
include = ["src/**/*.rs", "crates-io.md", "README.md", "LICENSE-APACHE", "LICENSE-MIT"] 

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.2"
directories = "3.0.2"
reqwest = { version = "0.11", features = ["json"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termcolor = "1.1.2"
tokio = { version = "1", features = ["full"] }
toml = { version = "0.5", features = ["preserve_order"] }
url = { version = "2.2.2", features = ["serde"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
